# Generated by Django 3.1.6 on 2021-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='Uid метка человека')),
                ('name', models.CharField(max_length=255, verbose_name='Имя человека')),
                ('surname', models.CharField(max_length=255, verbose_name='Имя человека')),
            ],
        ),
    ]
