# Generated by Django 3.1.6 on 2021-02-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_ID', models.CharField(max_length=255, verbose_name='Мембер ID')),
                ('allowed_members', models.BooleanField(default=False, verbose_name='Авторизован ли')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
